### ISSUE TITLE
Ordfs changed about a week ago and no longer handles BRC69 style recursion correctly

### ISSUE THREAD

**Issue by shiftshapr** [shruggr/ordfs-server#12]
Ordfs changed about a week or so ago and since no longer handles BRC69 style recursion correctly.

Here is an example that used to work but no longer works. 
https://www.ord.io/36572042

Here is the html:
<script t="0,15,36,19,22,65,92" src="/content/4c7d741841ac225074e8092818fda89c7c3c3be4639f392159baba230e80ebc2i0" m='{"p":"brc69" "op":"mint" "s":"metaweb_punks_test" "id":"1"}'></script>

Blank screen on ordfs but it works on inscriptions.  Used to work.

**Comment by shiftshapr** [comment]
Uncaught TypeError: Cannot redefine property: ethereum
    at Function.defineProperties (<anonymous>)
    at inpage.js:1:1505040
    at inpage.js:1:1505983
    at inpage.js:1:1505987
(index):62 cdn.tailwindcss.com should not be used in production. To use Tailwind CSS in production, install it as a PostCSS plugin or use the Tailwind CLI: https://tailwindcss.com/docs/installation
(anonymous) @ (index):62
ace.min.js:1 misspelled option "enableBasicAutocompletion"
i @ ace.min.js:1
ace.min.js:1 misspelled option "enableLiveAutocompletion"
i @ ace.min.js:1
(index):412 Object
4c7d741841ac225074e8092818fda89c7c3c3be4639f392159baba230e80ebc2i0:1 
        
        
       Failed to load resource: the server responded with a status of 500 ()
(index):104 Object
/content/7286fc9119a7630bad27f98459d81802ad2e100f78ba0ab993bbf0546ad9f730i0:1 
        
        
       Failed to load resource: the server responded with a status of 500 ()
contentScript.js:160 Uncaught SecurityError: Failed to read the 'sessionStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.
 Refused to connect to 'https://api.trongrid.io/wallet/getnodeinfo' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

(anonymous) @ inpage.js:45
 Refused to connect to 'https://api.trongrid.io/wallet/getnodeinfo' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

(anonymous) @ inpage.js:45
 [object DOMException]
23Blocked script execution in '<URL>' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
25Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('null').
(index):369 
(index):369 <script t="0,14,33,49,17,23,82" src="/content/4c7d741841ac225074e8092818fda89c7c3c3be4639f392159baba230e80ebc2i0" m='{"p":"brc69" "op":"mint" "s":"metaweb_punks_1" "id":"5"}'></script>

4c7d741841ac225074e8092818fda89c7c3c3be4639f392159baba230e80ebc2i0:1 
        
        
       Failed to load resource: the server responded with a status of 500 ()
PHNjcmlwdCB0PSIwLDE0LDMzLDQ5LDE3LDIzLDgyIiBzcmM9Ii9jb250ZW50LzRjN2Q3NDE4NDFhYzIyNTA3NGU4MDkyODE4ZmRhODljN2MzYzNiZTQ2MzlmMzkyMTU5YmFiYTIzMGU4MGViYzJpMCIgbT0neyJwIjoiYnJjNjkiICJvcCI6Im1pbnQiICJzIjoibWV0YXdlYl9wdW5rc18xIiAiaWQiOiI1In0nPjwvc2NyaXB0Pgo=:1 Refused to execute script from 'https://ordfs.network/content/4c7d741841ac225074e8092818fda89c7c3c3be4639f392159baba230e80ebc2i0' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
